### ISSUE TITLE
Issues with Diana 1.0.0

### ISSUE THREAD

**Issue by somakray** [fickludd/diana2#1]
Hello,

I'm trying to run diana-1.0.0 with the tutorial files. However I'm getting the following  error:

```
INFO Attempting to run   java -jar '/bin/diana/bin/jar/DianaExtractor-0.3.0.jar' --ms-resolution=20 --mode=uniform --dia-windows=gillet --isotopes=3 --out-dir='~/Desktop/DIANA_BASE/diana-tutorial/gold_std_120225_009.mzML' 'input/gold_std_120225_009.mzML.gz' input/target_345_aquas.traml input/decoy_345_aquas.traml input/irt-kit-final.traml
 DEBUG java stdout:
DianaExtractor 0.3.0
  swath mzML file: input/gold_std_120225_009.mzML.gz
     num isotopes: 3
   sub sample ms1: 1
            force: true
     max diff PPM: 20
      max diff Da: 0.0
  extraction mode: uniform
      traML files:
    input/target_345_aquas.traml
    input/decoy_345_aquas.traml
    input/irt-kit-final.traml

HANDLING FILE input/gold_std_120225_009.mzML.gz
      num spectra: 78012
|                    |
|====================|
DONE WITH input/gold_std_120225_009.mzML.gz

 heap size before writing: 1073 / 2330 Mb

 writing output file: ~/Desktop/DIANA_BASE/diana-tutorial/gold_std_120225_009.mzML/target_345_aquas.chrom.mzML

 DEBUG java stderr:
Exception in thread "main" java.io.FileNotFoundException: ~/Desktop/DIANA_BASE/diana-tutorial/gold_std_120225_009.mzML/target_345_aquas.chrom.mzML (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at java.io.FileWriter.<init>(FileWriter.java:90)
    at se.lth.immun.diana.DianaExtractor$$anonfun$handleSwathFile$1.apply$mcVI$sp(DianaExtractor.scala:299)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:142)
    at se.lth.immun.diana.DianaExtractor$.handleSwathFile(DianaExtractor.scala:276)
    at se.lth.immun.diana.DianaExtractor$.main(DianaExtractor.scala:224)
    at se.lth.immun.diana.DianaExtractor.main(DianaExtractor.scala)

 WARNI java failed with exit code 1

    #%&8! ANALYSIS FAILED IN SECTION CHROMATOGRAM EXTRACT AND SCORE
    ===============================================================
Traceback (most recent call last):
  File "/bin/diana/bin/diana", line 384, in <module>
    sectionLog.toFile(dianaRunID + ".section.csv")
  File "/bin/diana/bin/diana", line 148, in toFile
    f = open(os.path.join(analysisDir, path), "w")
IOError: [Errno 2] No such file or directory: '~/Desktop/DIANA_BASE/diana-tutorial/2016-06-20-12_29_07-DIANA_RUN.section.csv'
```

**Comment by fickludd** [comment]
Thank you for reporting this issue, but the DIANA 1.x is no longer maintained. I would recommend to use DIANA 2.x instead which should yield better performance and robustness unless you are memory-starved.
